# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded tabs::vfshandler 1.0 [list source [file join $dir vfshandler.tcl]]
package ifneeded tabs::vfshandler::cookfs 1.0 [list source [file join $dir cookfs.tcl]]
package ifneeded tabs::vfshandler::mk4 1.0 [list source [file join $dir mk4.tcl]]
package ifneeded tabs::vfshandler::zip 1.0 [list source [file join $dir zip.tcl]]
