# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded tabs::job::copy 1.0 [list source [file join $dir copy.tcl]]
package ifneeded tabs::job::repack 1.0 [list source [file join $dir repack.tcl]]
package ifneeded tabs::job::split 1.0 [list source [file join $dir split.tcl]]
package ifneeded tabs::job::tclscript 1.0 [list source [file join $dir tclscript.tcl]]
package ifneeded tabs::job::unwrap 1.0 [list source [file join $dir unwrap.tcl]]
package ifneeded tabs::job::wrap 1.0 [list source [file join $dir wrap.tcl]]
package ifneeded tabs::jobs 1.0 [list source [file join $dir jobs.tcl]]
